### ISSUE TITLE
problem with installing on fish shell

### ISSUE THREAD

**Issue by alec-c4** [benhoskings/babushka#317]
When i try to install babushka on fish shell (you can install this shell via brew install fish) i got a error message

```
sh: #!/bin/sh: No such file or directory
```

how can i fix it?

**Comment by Domon** [comment]
@benhoskings I have the same problem on fish shell. `bash -c` does not fix it.

```
> bash -c "`curl https://babushka.me/up`"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6991  100  6991    0     0   6541      0  0:00:01  0:00:01 --:--:--  6545
bash: #!/bin/sh: No such file or directory
```

I can confirm that `sh` is not linked to `fish`.

```
> /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by benhoskings** [comment]
This is a symptom of fish's divergence from standard `sh` behaviour. It's something to do with how the ```"`cmd`"``` construction works on fish, since that part is evaluated by fish in your case no matter what shell you specify in the command.

You can confirm by running another script on your system in the same way and observing the same failure: ```bash -c "`/another/script`"```

I doubt it's fixable within the script itself without breaking `sh` compatibility.
